export const Icons = [
  { id: "C++", img: "/images/languageIcons/cpp.png" },
  { id: "C#", img: "/images/languageIcons/csharp.png" },
  { id: "CSS", img: "/images/languageIcons/css.png" },
  { id: "Dart", img: "/images/languageIcons/dart.png" },
  { id: "Haskell", img: "/images/languageIcons/haskell.png" },
  { id: "HTML", img: "/images/languageIcons/html.png" },
  { id: "Java", img: "/images/languageIcons/java.png" },
  { id: "JavaScript", img: "/images/languageIcons/javascript.png" },
  { id: "Jupyter Notebook", img: "/images/languageIcons/jupiter.png" },
  { id: "Objective-C++", img: "/images/languageIcons/objectiveC.png" },
  { id: "PHP", img: "/images/languageIcons/php.png" },
  { id: "Python", img: "/images/languageIcons/python.png" },
  { id: "Ruby", img: "/images/languageIcons/ruby.png" },
  { id: "TypeScript", img: "/images/languageIcons/typescript.png" },
];
